FROM alpine:3.14
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories \
    && apk update \
    && apk add tzdata \
    && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone
WORKDIR /weekly-assistant
# 将二进制文件从 /build 目录复制到这里
COPY configs /weekly-assistant/configs
COPY bin/weekly-assistant.bin /usr/local/bin

# 启动容器时运行的命令
WORKDIR /weekly-assistant
CMD weekly-assistant.bin /weekly-assistant/configs/