package services

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"
)

func JsonToLang(jsonStr, lang string) (string, error) {
	var data interface{}
	if err := json.Unmarshal([]byte(jsonStr), &data); err != nil {
		return "", fmt.Errorf("invalid json: %w", err)
	}

	switch lang {
	case "go":
		return jsonToGo(data)
	case "java":
		return jsonToJava(data)
	case "python":
		return jsonToPython(data)
	case "typescript":
		return jsonToTypeScript(data)
	case "rust":
		return jsonToRust(data)
	case "swift":
		return jsonToSwift(data)
	case "cpp":
		return jsonToCpp(data)
	case "csharp":
		return jsonToCsharp(data)
	case "kotlin":
		return jsonToKotlin(data)
	case "php":
		return jsonToPHP(data)
	default:
		return "", fmt.Errorf("unsupported language: %s", lang)
	}
}

func jsonToGo(data interface{}) (string, error) {
	m, ok := data.(map[string]interface{})
	if !ok {
		return "", fmt.Errorf("root must be an object for Go struct generation")
	}
	name := "AutoGenerated"
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("type %s struct {\n", name))
	writeGoFields(sb, m, 1)
	sb.WriteString("}\n")
	return sb.String(), nil
}

func writeGoFields(sb *strings.Builder, m map[string]interface{}, depth int) {
	keys := sortedKeys(m)
	indent := strings.Repeat("\t", depth)
	for _, k := range keys {
		v := m[k]
		fieldName := toPascal(k)
		goType := goTypeOf(v, depth)
		jsonTag := fmt.Sprintf("`json:\"%s\"`", k)
		sb.WriteString(fmt.Sprintf("%s%s %s %s\n", indent, fieldName, goType, jsonTag))
	}
}

func goTypeOf(v interface{}, depth int) string {
	if v == nil {
		return "interface{}"
	}
	switch val := v.(type) {
	case bool:
		return "bool"
	case float64:
		if val == float64(int64(val)) {
			return "int"
		}
		return "float64"
	case string:
		return "string"
	case []interface{}:
		if len(val) > 0 {
			elem := goTypeOf(val[0], depth)
			return "[]" + elem
		}
		return "[]interface{}"
	case map[string]interface{}:
		return "struct {\n" + goInlineFields(val, depth+1) + strings.Repeat("\t", depth) + "}"
	default:
		return "interface{}"
	}
}

func goInlineFields(m map[string]interface{}, depth int) string {
	sb := &strings.Builder{}
	keys := sortedKeys(m)
	indent := strings.Repeat("\t", depth)
	for _, k := range keys {
		v := m[k]
		fieldName := toPascal(k)
		gt := goTypeOf(v, depth)
		jsonTag := fmt.Sprintf("`json:\"%s\"`", k)
		sb.WriteString(fmt.Sprintf("%s%s %s %s\n", indent, fieldName, gt, jsonTag))
	}
	return sb.String()
}

func jsonToJava(data interface{}) (string, error) {
	m, ok := data.(map[string]interface{})
	if !ok {
		return "", fmt.Errorf("root must be an object for Java class generation")
	}
	name := "AutoGenerated"
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("public class %s {\n", name))
	keys := sortedKeys(m)
	for _, k := range keys {
		v := m[k]
		t := javaTypeOf(v)
		sb.WriteString(fmt.Sprintf("    private %s %s;\n", t, toCamel(k)))
	}
	sb.WriteString("\n")
	for _, k := range keys {
		v := m[k]
		t := javaTypeOf(v)
		p := toPascal(k)
		c := toCamel(k)
		sb.WriteString(fmt.Sprintf("    public %s get%s() { return %s; }\n", t, p, c))
		sb.WriteString(fmt.Sprintf("    public void set%s(%s %s) { this.%s = %s; }\n", p, t, c, c, c))
	}
	sb.WriteString("}\n")
	return sb.String(), nil
}

func javaTypeOf(v interface{}) string {
	if v == nil {
		return "Object"
	}
	switch val := v.(type) {
	case bool:
		return "Boolean"
	case float64:
		if val == float64(int64(val)) {
			return "Integer"
		}
		return "Double"
	case string:
		return "String"
	case []interface{}:
		if len(val) > 0 {
			return "List<" + javaTypeOf(val[0]) + ">"
		}
		return "List<Object>"
	case map[string]interface{}:
		return "Map<String, Object>"
	default:
		return "Object"
	}
}

func jsonToPython(data interface{}) (string, error) {
	m, ok := data.(map[string]interface{})
	if !ok {
		return "", fmt.Errorf("root must be an object for Python class generation")
	}
	name := "AutoGenerated"
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("class %s:\n", name))
	sb.WriteString("    def __init__(self):\n")
	keys := sortedKeys(m)
	for _, k := range keys {
		v := m[k]
		t := pythonTypeHint(v)
		sb.WriteString(fmt.Sprintf("        self.%s: %s = None\n", toSnake(k), t))
	}
	return sb.String(), nil
}

func pythonTypeHint(v interface{}) string {
	if v == nil {
		return "Any"
	}
	switch val := v.(type) {
	case bool:
		return "bool"
	case float64:
		if val == float64(int64(val)) {
			return "int"
		}
		return "float"
	case string:
		return "str"
	case []interface{}:
		if len(val) > 0 {
			return "List[" + pythonTypeHint(val[0]) + "]"
		}
		return "List"
	case map[string]interface{}:
		return "Dict[str, Any]"
	default:
		return "Any"
	}
}

func jsonToTypeScript(data interface{}) (string, error) {
	m, ok := data.(map[string]interface{})
	if !ok {
		return "", fmt.Errorf("root must be an object for TypeScript interface generation")
	}
	name := "AutoGenerated"
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("interface %s {\n", name))
	keys := sortedKeys(m)
	for _, k := range keys {
		v := m[k]
		t := tsTypeOf(v)
		sb.WriteString(fmt.Sprintf("  %s: %s;\n", k, t))
	}
	sb.WriteString("}\n")
	return sb.String(), nil
}

func tsTypeOf(v interface{}) string {
	if v == nil {
		return "any"
	}
	switch val := v.(type) {
	case bool:
		return "boolean"
	case float64:
		if val == float64(int64(val)) {
			return "number"
		}
		return "number"
	case string:
		return "string"
	case []interface{}:
		if len(val) > 0 {
			return tsTypeOf(val[0]) + "[]"
		}
		return "any[]"
	case map[string]interface{}:
		return "{ [key: string]: any }"
	default:
		return "any"
	}
}

func jsonToRust(data interface{}) (string, error) {
	m, ok := data.(map[string]interface{})
	if !ok {
		return "", fmt.Errorf("root must be an object for Rust struct generation")
	}
	name := "AutoGenerated"
	sb := &strings.Builder{}
	sb.WriteString("#[derive(Debug, Serialize, Deserialize)]\n")
	sb.WriteString(fmt.Sprintf("pub struct %s {\n", name))
	keys := sortedKeys(m)
	for _, k := range keys {
		v := m[k]
		t := rustTypeOf(v)
		sb.WriteString(fmt.Sprintf("    pub %s: %s,\n", toSnake(k), t))
	}
	sb.WriteString("}\n")
	return sb.String(), nil
}

func rustTypeOf(v interface{}) string {
	if v == nil {
		return "Option<serde_json::Value>"
	}
	switch val := v.(type) {
	case bool:
		return "bool"
	case float64:
		if val == float64(int64(val)) {
			return "i64"
		}
		return "f64"
	case string:
		return "String"
	case []interface{}:
		if len(val) > 0 {
			return "Vec<" + rustTypeOf(val[0]) + ">"
		}
		return "Vec<serde_json::Value>"
	case map[string]interface{}:
		return "std::collections::HashMap<String, serde_json::Value>"
	default:
		return "serde_json::Value"
	}
}

func jsonToSwift(data interface{}) (string, error) {
	m, ok := data.(map[string]interface{})
	if !ok {
		return "", fmt.Errorf("root must be an object for Swift struct generation")
	}
	name := "AutoGenerated"
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("struct %s: Codable {\n", name))
	keys := sortedKeys(m)
	for _, k := range keys {
		v := m[k]
		t := swiftTypeOf(v)
		sb.WriteString(fmt.Sprintf("    let %s: %s\n", toCamel(k), t))
	}
	sb.WriteString("}\n")
	return sb.String(), nil
}

func swiftTypeOf(v interface{}) string {
	if v == nil {
		return "Any?"
	}
	switch val := v.(type) {
	case bool:
		return "Bool"
	case float64:
		if val == float64(int64(val)) {
			return "Int"
		}
		return "Double"
	case string:
		return "String"
	case []interface{}:
		if len(val) > 0 {
			return "[" + swiftTypeOf(val[0]) + "]"
		}
		return "[Any]"
	case map[string]interface{}:
		return "[String: Any]"
	default:
		return "Any"
	}
}

func jsonToCpp(data interface{}) (string, error) {
	m, ok := data.(map[string]interface{})
	if !ok {
		return "", fmt.Errorf("root must be an object for C++ struct generation")
	}
	name := "AutoGenerated"
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("struct %s {\n", name))
	keys := sortedKeys(m)
	for _, k := range keys {
		v := m[k]
		t := cppTypeOf(v)
		sb.WriteString(fmt.Sprintf("    %s %s;\n", t, toSnake(k)))
	}
	sb.WriteString("};\n")
	return sb.String(), nil
}

func cppTypeOf(v interface{}) string {
	if v == nil {
		return "std::any"
	}
	switch val := v.(type) {
	case bool:
		return "bool"
	case float64:
		if val == float64(int64(val)) {
			return "int"
		}
		return "double"
	case string:
		return "std::string"
	case []interface{}:
		if len(val) > 0 {
			return "std::vector<" + cppTypeOf(val[0]) + ">"
		}
		return "std::vector<std::any>"
	case map[string]interface{}:
		return "std::map<std::string, std::any>"
	default:
		return "std::any"
	}
}

func jsonToCsharp(data interface{}) (string, error) {
	m, ok := data.(map[string]interface{})
	if !ok {
		return "", fmt.Errorf("root must be an object for C# class generation")
	}
	name := "AutoGenerated"
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("public class %s\n{\n", name))
	keys := sortedKeys(m)
	for _, k := range keys {
		v := m[k]
		t := csharpTypeOf(v)
		p := toPascal(k)
		sb.WriteString(fmt.Sprintf("    public %s %s { get; set; }\n", t, p))
	}
	sb.WriteString("}\n")
	return sb.String(), nil
}

func csharpTypeOf(v interface{}) string {
	if v == nil {
		return "object"
	}
	switch val := v.(type) {
	case bool:
		return "bool"
	case float64:
		if val == float64(int64(val)) {
			return "int"
		}
		return "double"
	case string:
		return "string"
	case []interface{}:
		if len(val) > 0 {
			return "List<" + csharpTypeOf(val[0]) + ">"
		}
		return "List<object>"
	case map[string]interface{}:
		return "Dictionary<string, object>"
	default:
		return "object"
	}
}

func jsonToKotlin(data interface{}) (string, error) {
	m, ok := data.(map[string]interface{})
	if !ok {
		return "", fmt.Errorf("root must be an object for Kotlin data class generation")
	}
	name := "AutoGenerated"
	sb := &strings.Builder{}
	sb.WriteString(fmt.Sprintf("data class %s(\n", name))
	keys := sortedKeys(m)
	for i, k := range keys {
		v := m[k]
		t := kotlinTypeOf(v)
		comma := ","
		if i == len(keys)-1 {
			comma = ""
		}
		sb.WriteString(fmt.Sprintf("    val %s: %s%s\n", toCamel(k), t, comma))
	}
	sb.WriteString(")\n")
	return sb.String(), nil
}

func kotlinTypeOf(v interface{}) string {
	if v == nil {
		return "Any?"
	}
	switch val := v.(type) {
	case bool:
		return "Boolean"
	case float64:
		if val == float64(int64(val)) {
			return "Int"
		}
		return "Double"
	case string:
		return "String"
	case []interface{}:
		if len(val) > 0 {
			return "List<" + kotlinTypeOf(val[0]) + ">"
		}
		return "List<Any>"
	case map[string]interface{}:
		return "Map<String, Any>"
	default:
		return "Any"
	}
}

func jsonToPHP(data interface{}) (string, error) {
	m, ok := data.(map[string]interface{})
	if !ok {
		return "", fmt.Errorf("root must be an object for PHP class generation")
	}
	name := "AutoGenerated"
	sb := &strings.Builder{}
	sb.WriteString("<?php\n\n")
	sb.WriteString(fmt.Sprintf("class %s\n{\n", name))
	keys := sortedKeys(m)
	for _, k := range keys {
		v := m[k]
		t := phpTypeOf(v)
		sb.WriteString(fmt.Sprintf("    private %s $%s;\n", t, toCamel(k)))
	}
	sb.WriteString("\n")
	for _, k := range keys {
		v := m[k]
		t := phpTypeOf(v)
		c := toCamel(k)
		p := toPascal(k)
		sb.WriteString(fmt.Sprintf("    public function get%s(): %s { return $this->%s; }\n", p, t, c))
		sb.WriteString(fmt.Sprintf("    public function set%s(%s $%s): void { $this->%s = $%s; }\n", p, t, c, c, c))
	}
	sb.WriteString("}\n")
	return sb.String(), nil
}

func phpTypeOf(v interface{}) string {
	if v == nil {
		return "mixed"
	}
	switch val := v.(type) {
	case bool:
		return "bool"
	case float64:
		if val == float64(int64(val)) {
			return "int"
		}
		return "float"
	case string:
		return "string"
	case []interface{}:
		return "array"
	case map[string]interface{}:
		return "array"
	default:
		return "mixed"
	}
}

func sortedKeys(m map[string]interface{}) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func toPascal(s string) string {
	parts := splitName(s)
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}

func toCamel(s string) string {
	parts := splitName(s)
	for i, p := range parts {
		if i == 0 {
			parts[i] = strings.ToLower(p)
		} else if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}

func toSnake(s string) string {
	parts := splitName(s)
	return strings.Join(parts, "_")
}

func splitName(s string) []string {
	var parts []string
	var cur []rune
	for _, r := range s {
		if r == '_' || r == '-' || r == ' ' {
			if len(cur) > 0 {
				parts = append(parts, string(cur))
				cur = nil
			}
		} else if len(cur) > 0 && r >= 'A' && r <= 'Z' && cur[len(cur)-1] >= 'a' && cur[len(cur)-1] <= 'z' {
			parts = append(parts, string(cur))
			cur = []rune{r}
		} else {
			cur = append(cur, r)
		}
	}
	if len(cur) > 0 {
		parts = append(parts, string(cur))
	}
	return parts
}
